version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR
      - aws ecr get-login-password --region eu-north-1 | docker login --username AWS --password-stdin 213936281972.dkr.ecr.eu-north-1.amazonaws.com

  build:
    commands:
      - echo Build started
      - docker build -t $ImageName .
      - docker tag $ImageName:latest 213936281972.dkr.ecr.eu-north-1.amazonaws.com/$ImageName:latest

  post_build:
    commands:
      - docker push 213936281972.dkr.ecr.eu-north-1.amazonaws.com/$ImageName:latest
     
artifacts:
  # include all files required to run the application
  files:
    - appspec.yml
    - dist/**/*
    - scripts/**/*
  discard-paths: no
    #- src/**/*
    #- package.json
    #- appspec.yml
    #- scripts/**/*
